# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Solace"
description: "InShorts: Everything you need to know about Solace"
baseurl: # the subpath of your site, e.g. "/blog"
url: "https://gvensan.github.io/solace-glossary/"
logo: "/assets/images/solace-logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 265
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Poppins"
    weights: "100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
  - name: "Kreon"
    weights: "300,400,500,600,700"
  - name: "DM Mono"
    weights: "300,300i,400,400i,500,500i"
google_analytics: "UA-107282718-2"
disqus:
  shortname: jordanlevi-red
twitter:
  username: swaminetero

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Jordan Levi
  picture: /assets/images/AuthorLogo.png
  email: swamintero@gmail.com
  links:
    - title: Twitter
      url: https://twitter.com/solacedotcom
      icon: fab fa-twitter
    - title: Instagram
      url: https://www.instagram.com/solacedotcom/
      icon: fab fa-instagram
    - title: Facebook
      url: https://www.facebook.com/solacedotcom
      icon: fab fa-facebook-f
    - title: Youtube
      url: https://www.youtube.com/solacedotcom
      icon: fab fa-youtube
    - title: Solace Community
      url: https://solace.community
      icon: fas fa-users
    - title: Solace.com
      url: https://solace.com/
      icon: fas fa-link

# Footer Links
footer_links:
    - title: Twitter
      url: https://twitter.com/solacedotcom
      icon: fab fa-twitter
    - title: Instagram
      url: https://www.instagram.com/solacedotcom/
      icon: fab fa-instagram
    - title: Facebook
      url: https://www.facebook.com/solacedotcom
      icon: fab fa-facebook-f
    - title: Youtube
      url: https://www.youtube.com/solacedotcom
      icon: fab fa-youtube
    - title: Solace Community
      url: https://solace.community
      icon: fas fa-users
    - title: Solace.com
      url: https://solace.com/
      icon: fas fa-link
    
# Powered By
copyright: Powered by <a href="http://jekyllrb.com/">Jekyll</a> using the <a href="https://github.com/mmistakes/so-simple-theme">So Simple Theme</a>